#%Module1.0
# The first line of this file tells Modules that this is a module file.
# DO NOT ALTER IT!
#
# ABOUT THIS FILE
#
# This file is designed to be processed by Python.  Specifically, this file
# will be read into a string, and the .format() method will be applied to it.
# This file is not a valid module file on its own.
#
# METADATA AND DOCUMENTATION SECTION
#
# This function is part of the Modules help system.  You can modify
# the second line if needed, but most products should
# leave this alone.
#
proc ModulesHelp {{ }} {{
    global product version
    puts stderr "This module adds $product/$version to your environment."
}}
#
# These variables are used below.  The product variable should be set to
# the name of the product and never changed.  The version variable will
# be set at install time, so it should be left alone.  The conflict line
# prevents multiple versions from being loaded simultaneously.  Do not
# change it.
#
set product desimodules
set version {version}
conflict $product
#
# The line below is another part of the Modules help system.  You can
# modify the part in quotes if you really need to, but most products should
# leave this alone.
#
module-whatis "Sets up $product/$version in your environment."
#
# DEPENDENCIES SECTION
#
# If your product requires other software to function, that should be declared
# here.  There are two types of dependencies: mandatory and optional.
# A mandatory dependency is a module load command followed by a prereq
# command.  An optional dependency is not followed by a prereq statement.
#
#- These are the external products that we need for most DESI work
#- They only exist on edison and carver for now.
if {{ [info exists env(NERSC_HOST)] }} {{
    if {{ $env(NERSC_HOST) == "edison" }} {{
        module load astropy-hpcp/1.0.1_32b25281-7.1
        module load scipy-hpcp/0.15.1_5a3d8dfa-7.1
        module load matplotlib-hpcp/1.4.3_f611a56c-7.1
        module load ipython-hpcp/3.0.0_368e8239-7.1
        module load yaml-hpcp/e05740ad_e05740ad-7.1
        module load fitsio-hpcp/d1fb9f2_99093b02-7.1
        module load requests-hpcp/2.8.1_a47b9456-7.1
    }} elseif {{ $env(NERSC_HOST) == "cori" }} {{
        module load astropy-hpcp/1.0.1_f4385b62-1.0
        module load scipy-hpcp/0.15.1_3ec027f3-1.0
        module load matplotlib-hpcp/1.4.3_5e44e5f1-1.0
        module load ipython-hpcp/3.0.0_c49d793a-1.0
        module load yaml-hpcp/62933e3b_62933e3b-1.0
        module load fitsio-hpcp/d1fb9f2_8bdd6887-1.0
        module load requests-hpcp/2.8.1_49aa3196-1.0
    }} elseif {{ $env(NERSC_HOST) == "hopper" }} {{
        module load astropy-hpcp/1.0.1_a75855cf-2.0
        module load scipy-hpcp/0.15.1_6a2ae39e-2.0
        module load matplotlib-hpcp/1.4.3_8adf7c64-2.0
        module load ipython-hpcp/3.0.0_ca09c690-2.0
        module load yaml-hpcp/da9c3d7c_da9c3d7c-2.0
        module load fitsio-hpcp/a2fdf07_8be048ab-2.0
    }} elseif {{ $env(NERSC_HOST) == "datatran" }} {{
        module load astropy-hpcp/1.0.1_f4385b62-1.0
        module load scipy-hpcp/0.15.1_3ec027f3-1.0
        module load matplotlib-hpcp/1.4.3_bfb50b98-1.0
        module load ipython-hpcp/3.0.0_c49d793a-1.0
        module load yaml-hpcp/62933e3b_62933e3b-1.0
        module load fitsio-hpcp/d1fb9f2_8bdd6887-1.0
        module load requests-hpcp/2.8.1_49aa3196-1.0
        module load subversion-hpcp
    }} elseif {{ $env(NERSC_HOST) == "scigate" }} {{
        module load astropy-hpcp/0.3.2_567b861f-1.0
        module load scipy-hpcp/0.14.0_2686a374-1.0
        module load matplotlib-hpcp/1.3.1_f5da6b43-1.0
        module load ipython-hpcp/0.13.2_f5da6b43-1.0
        module load yaml-hpcp/d12183c4_d12183c4-1.0
        module load fitsio-hpcp/a2fdf07_d424107f-1.0
    }}
    prereq astropy-hpcp
    prereq scipy-hpcp
    prereq matplotlib-hpcp
    prereq ipython-hpcp
    prereq yaml-hpcp
    prereq fitsio-hpcp
}}


#- DESI specific modules
module load desiutil
prereq desiutil
module load desitree
prereq desitree

module load desimodel/0.3.8


#
# ENVIRONMENT SECTION
#
# The PRODUCT_ROOT and PRODUCT_DIR variables are used to set other
# environment variables but are not exported to the actual environment.
# If you are not working at NERSC, but still want to use Modules, you
# will need to set the DESI_PRODUCT_ROOT environment variable
#
if {{[info exists env(DESI_PRODUCT_ROOT)]}} {{
    set PRODUCT_ROOT $env(DESI_PRODUCT_ROOT)
}} else {{
    set PRODUCT_ROOT /project/projectdirs/desi/software/$env(NERSC_HOST)
}}
set PRODUCT_DIR $PRODUCT_ROOT/$product/$version
#
# This line creates an environment variable pointing to the install
# directory of your product.
#
setenv [string toupper $product] $PRODUCT_DIR
#
# The lines below set various other environment variables.  They assume the
# template product layout.  These will be set or commented as needed by the
# desiInstall script.
#
## prepend-path PATH $PRODUCT_DIR/bin
## prepend-path PYTHONPATH $PRODUCT_DIR/py
## prepend-path LD_LIBRARY_PATH $PRODUCT_DIR/lib
#
# Add any non-standard Module code below this point.
#
